version: '2'

services:
  mdldb:
    image: mysql:5.5.59
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/moodle-mysql.cnf:/etc/mysql/conf.d"
    env_file:
      - "./moodle-variables.env"
    ports:
      - "3306:3306"

  mdlapp:
    build: ./php5
    volumes:
      - "./public:/var/www/html"
      - "./php5/moodledata:/var/www/moodledata"
    ports:
      - "80:80"
    depends_on:
      - mdldb
